version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: scripts/install_deps.sh
      timeout: 300
      runas: root
    - location: scripts/start_container.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 300
      runas: root
